#!/bin/sh

# Include the wrappers utility script
. /usr/lib/java-wrappers/java-wrappers.sh

find_java_runtime

JAVA_CLASSPATH=/usr/share/java/derbyclient.jar:/usr/share/java/derbytools.jar:/usr/share/java/derbynet.jar:/usr/share/java/servlet-api-3.1.jar

run_java org.apache.derby.tools.dblook "$@"
