#!/bin/sh

# Include the wrappers utility script
. /usr/lib/java-wrappers/java-wrappers.sh

find_java_runtime

JAVA_CLASSPATH=/usr/share/java/derbyclient.jar:/usr/share/java/derbytools.jar

run_java org.apache.derby.tools.sysinfo "$@"
